version: 2
sources:
  - name: northwind
    schema: northwind_el
    description: This is the northwind erp postgres database replica
    tables:
      - name: order_details
        description: One record per order. Includes cancelled and deleted orders.
        columns:
          - name: order_id
            description: Primary key of the orders table
            tests:
              - unique
              - not_null
          - name: status
            description: Note that the status can change over time

          - name: order_details
      - name: products
      - name: shippers
      - name: employees
      - name: customers
      - name: suppliers
      - name: categories
      

          #  - name: public_categories
          #  - name: public_custumers
          #  - name: public_employee_territories
          #  - name: public_employees
          #  - name: public_order_details
          #  - name: public_orders_
          #  - name: public_products
          #  - name: public_shippers_
          #  - name: public_supplers_
          #  - name: public_territories_