version: 2

sources:
  - name: northwind
    schema: northwind_el
    description: This is the northwind erp postgres database replica
    tables:
      - name: orders
        description: One record per order. Includes cancelled and deleted orders.
        columns:
          - name: order_id
            description: Primary key of the orders table
            tests:
              - unique
              - not_null
          - name: status
            description: Note that the status can change over time

      - name: public_order_details
      - name: public_products
      - name: public_shippers_
      - name: public_employees
      - name: public_custumers
      - name: public_supplers_
      - name: public_categories
      